Feature 65
equinix-labs/ansible-collection-equinix pull request #107
Opened 2023-08-01 13:13 UTC by AlexBacho

implements https://github.com/equinix-labs/ansible-collection-equinix/issues/65

2023-08-02 07:57 UTC, t0mk reviewed
We usually call the PRs based on the content, not by the issue they fix, so this could be "Add modules metal_project_ssh_key{_info}, docs and tests"

2023-08-02 08:35 UTC, t0mk requested changes

2023-08-02 08:35 UTC, t0mk commented on plugins/modules/metal_project_ssh_key.py
> +    print("!!!!!!!!!!!!!")
Maybe you forgot debug prints here?

`print()` usually doesn't work in Ansible modules, because Ansible is hijacking stdout <- IMO one of the worst things about developing Ansible modules. I use
https://github.com/zestyping/q
.. for debugging

2023-08-02 08:35 UTC, t0mk commented on requirements.txt
> +pydantic==1.10.2
this shuold come in a separate PR

2023-08-02 08:35 UTC, t0mk commented on plugins/modules/metal_project_ssh_key.py
> +      project_id: "local.project_id"
project IDs (and any IDs in Equinix MEtal) are uuids (e.g. 7c7e9e99-71cf-4425-90d7-b9c950d25705) , so the example should also show some uuid. Also it's better to put it in quotes so that it's in quotes in generated markdown.

Please fix this in all the docs, I won't comment on every occurrence.

2023-08-02 08:35 UTC, t0mk commented on README.md
> +list project SSH keys
Not sure how this rogue line got here. We don't write README.md by hand. If we need to change readme, we do it in the template/README.template.md

2023-08-02 08:35 UTC, t0mk commented on plugins/module_utils/metal/api_routes.py
> +        ('metal_project_ssh_key', action.GET): spec_types.Specs(
as the API route for getting user ssh keys and project ssh keys by ID is the same, we could remove this particular route, and do this in `metal_project_ssh_key.py`:

```python
    try:
        module.params_syntax_check()
        if module.params.get("id"):
            tolerate_not_found = state == "absent"
            # API getter is the same for user and project key
            fetched = module.get_by_id("metal_ssh_key", tolerate_not_found)
        else:
            fetched = module.get_one_from_list(
                # API listing method is different for project keys
                "metal_project_ssh_key",
                ["key"],
            )
```

That way there will be less code to maintain

2023-08-02 08:35 UTC, t0mk commented on plugins/module_utils/metal/api_routes.py
> +        ('metal_project_ssh_key', action.DELETE): spec_types.Specs(
please remove this route, and do

``` 
module.delete_by_id("metal_ssh_key")
```
in `metal_project_ssh_key.py`

2023-08-02 08:35 UTC, t0mk commented on plugins/module_utils/metal/api_routes.py
> +        ('metal_project_ssh_key', action.UPDATE): spec_types.Specs(
please remove this route, and do
```
fetched = module.update_by_id(diff, "metal_ssh_key")
```
in `metal_project_ssh_key.py`

2023-08-02 18:01 UTC, AlexBacho commented on requirements.txt
> +pydantic==1.10.2
all integration tests fail without this, will need to address it before merging this pr

2023-08-04 08:18 UTC, t0mk commented
I'm not sure how to run the integration tests here in the PR. This
https://github.com/equinix-labs/ansible-collection-equinix/blob/main/.github/workflows/integration-tests.yml
..should trigger but didn't, probably because Alex doesn't have a role in the repo. I think we should have a command to run the tests or PR by external people.

2023-08-04 11:04 UTC, t0mk approved these changes

2023-08-04 11:05 UTC, t0mk commented
Looks good but let's merge #108 first

2023-08-15 11:06 UTC, t0mk submitted a review, later dismissed
I reviewed before, so here I'm just approving

2023-08-15 11:19 UTC, t0mk approved these changes
I reviewed before (twice), so here I'm just approving

2023-08-15 11:19 UTC, merged