WIP implements metal connection, info and integration tests
equinix-labs/ansible-collection-equinix pull request #118
Opened 2023-08-21 22:00 UTC by AlexBacho

work in progress

2023-09-05 21:52 UTC, AlexBacho commented
I get a 500 unhandled exception when creating a shared primary connection, any idea what is causing this?

![image](https://github.com/equinix-labs/ansible-collection-equinix/assets/51121296/583c716a-f0aa-45e6-a365-5c48221da1a7)

2023-09-08 12:01 UTC, t0mk commented
> I get a 500 unhandled exception when creating a shared primary connection, any idea what is causing this?
> 
> ![image](https://user-images.githubusercontent.com/51121296/265834373-583c716a-f0aa-45e6-a365-5c48221da1a7.png)

This might be a misconfiguration for connection. Probably an API issue. TF doesn't sanitize this.

2023-09-08 21:59 UTC, AlexBacho commented
should be ready for review

2023-09-11 09:12 UTC, t0mk requested changes

2023-09-11 09:12 UTC, t0mk commented on tests/integration/targets/metal_connection/tasks/main.yml
> +    - name: delete test connections
This sweeper tasks fails with a strange error:

https://github.com/equinix-labs/ansible-collection-equinix/actions/runs/6126775492/job/16667433022#step:9:114

@AlexBacho does it happen in your local environment too?

2023-09-17 18:44 UTC, AlexBacho commented on plugins/modules/metal_connection.py
> +    """
either 'connection_id' or 'name' is required for fetching a connection, just using the 'id' parameter isn't allowed.

2023-09-17 19:03 UTC, AlexBacho commented on tests/integration/targets/metal_connection/tasks/main.yml
> +    - name: delete test connections
i think it's because the list endpoint also returns dedicated (organization) connections, despite no organization_id being specifield, and deleting that isn't allowed... ill remove it

2023-09-20 20:32 UTC, displague commented on plugins/modules/metal_connection.py
> +    """
That doesn't seem to be the case in Terraform: https://github.com/equinix/terraform-provider-equinix/blob/main/equinix/data_source_metal_connection.go#L100-L104

The API endpoint only requires a connection ID in the path:
https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/getInterconnection

2023-09-20 21:59 UTC, AlexBacho commented on plugins/modules/metal_connection.py
> +    """
What I meant is that there are two "ids" in the response dict. "Connection_id" and "Id", they hold the same value, but for the fetch method, using the "id" param by itself raises a validation error. I added a check into "metal_connection.py" that will set connection_id to id if it isn't provided.

What I don't understand is why "name" by itself works without proving connection_id, since connection_id is set to required.

2023-09-21 12:07 UTC, t0mk commented
@AlexBacho we will need to rework this a bit still. With the API update and with new equinix_metal pip package, you can see that InterconnectionCreateInput class is not genreated anymore. Instead it's defined as oneOf[0], and there is
for type == "dedicated": https://github.com/equinix-labs/metal-python/blob/main/equinix_metal/docs/DedicatedPortCreateInput.md
for type =="shared": https://github.com/equinix-labs/metal-python/blob/main/equinix_metal/docs/VrfFabricVcCreateInput.md

https://github.com/equinix-labs/metal-python/blob/main/oas3.fetched/components/requestBodies/InterconnectionCreateInput.yaml

You will need to update equinix_metal to the latest release to see the new input classes. Please also fix equinix_metal to the newest equinix_metal release in requirements.yml.

2023-09-21 12:45 UTC, t0mk commented
@AlexBacho I looked a bit more on the API[0]. It seems that there's a way to create IC in project[1] or in an org[2]. The module should handle both. The API input to either of those two can be any of the three [3].

We have 6 combinations here which is not good. We need to think how to handle those in the api_router[4], because in the CREATOR routes, we have a combination of APImethod-Input, I think we'll need 6 entries there 

metal_connection_project_dedicated
metal_connection_project_vlanfabric
metal_connection_project_vrf
metal_connection_organization_dedicated
metal_connection_organization_vlanfabric
metal_connection_organization_vrf

.. in form 
```python
        ('`metal_connection_organization_vlanfabric', action.CREATE): spec_types.Specs(
            equinix_metal.InterconnectionsApi(mpc).metal_connection_organization_vlanfabric,
            {'organization_id': 'organization_id'},  # see the args of the function in [5] 
            equinix_metal.DedicatedPortCreateInput,
        ),
```
.. I think you understand what the configuration should be for the other routes.

You will need to distinguish those for the create event in the module. I do sth similar but much simpler in the metal_project, line 245 [6]. As for the GETTER and UPDATER, there's only one of each [7,8]. As for listers there will be 2 [9,10] (you will need them in `metal_connection_info`, where there should be two exclusive params `project_id` and `organization_id`.

You don't need to implement the fetch by name in `metal_connection`. Just by ID. It's a pretty bad practice anyway, I shouldn't have done in the collection.

I hope this is clear, let's talk tomorrow.

[0] https://deploy.equinix.com/developers/api/metal#tag/Interconnections
[1] https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/createProjectInterconnection
[2] https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/createOrganizationInterconnection
[3] https://github.com/equinix-labs/metal-python/blob/main/oas3.fetched/components/requestBodies/InterconnectionCreateInput.yaml
[4] https://github.com/equinix-labs/ansible-collection-equinix/blob/main/plugins/module_utils/metal/api_routes.py
[5] https://github.com/equinix-labs/metal-python/blob/main/equinix_metal/equinix_metal/api/interconnections_api.py#L223
[6] https://github.com/equinix-labs/ansible-collection-equinix/blob/main/plugins/modules/metal_project.py#L245
[7] https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/getInterconnection
[8] https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/updateInterconnection
[9] https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/organizationListInterconnections
[10] https://deploy.equinix.com/developers/api/metal#tag/Interconnections/operation/projectListInterconnections

2023-10-06 10:16 UTC, t0mk requested changes
@AlexBacho  Please fix my latests suggestions, regenerate docs and push.

You did improvements to vlan and project_ssh_key, it's a good intiative, but next time they should go to a separate PR.

2023-10-06 10:16 UTC, t0mk commented on plugins/module_utils/metal/spec_types.py
> +import q
```suggestion
```

2023-10-06 10:16 UTC, t0mk commented on plugins/module_utils/metal/spec_types.py
> +import q
this needs to go out

2023-10-06 10:16 UTC, t0mk commented on plugins/module_utils/metal/spec_types.py
> +        q(self.conf.func, self.sdk_kwargs)
```suggestion
```

2023-10-06 10:16 UTC, t0mk commented on plugins/module_utils/metal/spec_types.py
> +        q(self.conf.func, self.sdk_kwargs)
my fault, this needs to go

2023-10-06 10:16 UTC, t0mk commented on plugins/modules/metal_vlan.py
> +    - UUID of vlan"
```suggestion
    - UUID of vlan
```

2023-10-06 10:16 UTC, t0mk commented on plugins/modules/metal_vlan.py
> +    - ID of parent project"
```suggestion
    - ID of parent project
```

2023-10-09 08:51 UTC, t0mk approved these changes

2023-10-09 08:51 UTC, merged