feat: metal virtual circuit
equinix-labs/ansible-collection-equinix pull request #141
Opened 2023-11-24 12:48 UTC by antoninrykalsky

2023-11-27 11:06 UTC, t0mk commented
@antoninrykalsky Thanks for the PR. We will wait for an Interconnection to test this properly.

2024-02-21 16:11 UTC, displague commented
Heads up that there is an upcoming requirement for VLAN in the requests: https://feedback.equinixmetal.com/changelog/virtual-circuits-will-require-vlans-on-feb-29-2024

Since this PR allows for `vlan` to be defined, it is fine that the user will receive a `422` from the API server prompting them to add `vlan` in their Ansible configuration.

2024-02-22 22:16 UTC, displague commented
I'd like to be able to include this in the v0.4.0 release in the next few weeks.

2024-02-27 22:15 UTC, displague commented
```
ansible-test integration metal_virtual_circuit
Running metal_virtual_circuit integration test role

PLAY [testhost] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [testhost]

TASK [metal_virtual_circuit : set_fact] ****************************************
ok: [testhost]

TASK [metal_virtual_circuit : set_fact] ****************************************
ok: [testhost]

TASK [metal_virtual_circuit : set_fact] ****************************************
ok: [testhost]

TASK [metal_virtual_circuit : set_fact] ****************************************
ok: [testhost]

TASK [metal_virtual_circuit : set_fact] ****************************************
ok: [testhost]

TASK [metal_virtual_circuit : create first project for test] *******************
changed: [testhost]

TASK [metal_virtual_circuit : create connection for test] **********************
changed: [testhost]

TASK [metal_virtual_circuit : Display test_connection] *************************
ok: [testhost] => {
    "test_connection": {
        "changed": true,
        "contact_email": "marques+tfacctest@packet.com",
        "description": "My new VLAN",
        "failed": false,
        "id": "8a2e639f-7efa-43b7-a8d4-26b2b99e61f4",
        "metro": {
            "code": "am",
            "country": "NL",
            "id": "108b2cfb-246b-45e3-885a-bf3e82fce1a0",
            "name": "Amsterdam"
        },
        "mode": "standard",
        "name": "ansible-integration-test-project-ar-denfnszy-TestConn",
        "ports": [
            {
                "href": "/metal/v1/connections/8a2e639f-7efa-43b7-a8d4-26b2b99e61f4/ports/7cb170a3-c254-4b5d-8abd-508e7dc87562",
                "id": "7cb170a3-c254-4b5d-8abd-508e7dc87562",
                "link_status": "unknown",
                "name": "ansible-integration-test-project-ar-denfnszy-TestConn-primary",
                "organization": {
                    "href": "/metal/v1/organizations/e965d662-e182-4f84-a43b-ff16c5d320bd"
                },
                "role": "primary",
                "speed": 50000000,
                "status": "requested",
                "virtual_circuits": []
            }
        ],
        "redundancy": "primary",
        "requested_by": {
            "href": "/metal/v1/users/72fe6383-b41f-4373-9f67-4bd5ec9a74a7",
            "id": "72fe6383-b41f-4373-9f67-4bd5ec9a74a7"
        },
        "status": "pending",
        "tags": [],
        "type": "dedicated"
    }
}

TASK [metal_virtual_circuit : Display test_metro_id] ***************************
ok: [testhost] => {
    "test_metro_id": "VARIABLE IS NOT DEFINED!"
}

TASK [metal_virtual_circuit : create VLAN resource no.1] ***********************
changed: [testhost]

TASK [metal_virtual_circuit : Display test_vlan] *******************************
ok: [testhost] => {
    "test_vlan": {
        "changed": true,
        "description": "This is my new VLAN 1.",
        "failed": false,
        "id": "9573b1af-97c3-493b-a674-9bd026db01ed",
        "metro": {
            "href": "/metal/v1/locations/metros/108b2cfb-246b-45e3-885a-bf3e82fce1a0",
            "id": "108b2cfb-246b-45e3-885a-bf3e82fce1a0"
        },
        "vxlan": 1234
    }
}

TASK [metal_virtual_circuit : create first virtual circuit for test] ***********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   none is not an allowed value (type=type_error.none.not_allowed)
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Error in metal_virtual_circuit: No match found when deserializing the JSON string into VirtualCircuitCreateInput with oneOf schemas: VlanVirtualCircuitCreateInput, VrfVirtualCircuitCreateInput. Details: 1 validation error for VlanVirtualCircuitCreateInput\nnni_vlan\n  value is not a valid integer (type=type_error.integer), 4 validation errors for VrfVirtualCircuitCreateInput\nnni_vlan\n  value is not a valid integer (type=type_error.integer)\npeer_asn\n  none is not an allowed value (type=type_error.none.not_allowed)\nsubnet\n  none is not an allowed value (type=type_error.none.not_allowed)\nvrf\n  none is not an allowed value (type=type_error.none.not_allowed)"}

TASK [metal_virtual_circuit : Announce teardown start] *************************
ok: [testhost] => {
    "msg": "***** TESTING COMPLETE. COMMENCE TEARDOWN *****"
}

TASK [metal_virtual_circuit : list test projects] ******************************
ok: [testhost]

TASK [metal_virtual_circuit : delete test projects] ****************************
changed: [testhost] => (item={'backend_transfer_enabled': True, 'customdata': {}, 'description': '', 'id': '08f99f1a-ed09-4149-a16e-87f37665a423', 'name': 'ansible-integration-test-project-ar-denfnszy-project1', 'organization_id': 'e965d662-e182-4f84-a43b-ff16c5d320bd', 'payment_method_id': ''})

PLAY RECAP *********************************************************************
testhost                   : ok=15   changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

2024-02-27 22:16 UTC, displague commented
It should be possible to test reading in the virtual circuit returned by a shared interconnection.

2024-02-27 22:40 UTC, displague commented on plugins/module_utils/metal/api_routes.py
> +            equinix_metal.VirtualCircuitCreateInput,
I'm unfamiliar with the patterns in this project. 
Is L279 correct? 

Is L280 expected to work with the single CreateInput type or perhaps does this resource need to be split up like `metal_connection_project_*` to accommodate the multiple input types: `VlanVirtualCircuitCreateInput`,`VrfVirtualCircuitCreateInput`?

2024-03-01 14:32 UTC, t0mk commented
@displague Can you please check that ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID was indeed set? Is it in the same "namespace" as the access token? We need to read it as envvar and it seems empty.

2024-03-06 20:00 UTC, displague commented
```
TASK [metal_virtual_circuit : create first project for test] *******************
changed: [testhost]

TASK [metal_virtual_circuit : Display test_connection] *************************
ok: [testhost] => {
    "test_connection": "VARIABLE IS NOT DEFINED!"
}

TASK [metal_virtual_circuit : create VLAN resource no.1] ***********************
changed: [testhost]

TASK [metal_virtual_circuit : Display test_vlan] *******************************
ok: [testhost] => {
    "test_vlan": {
        "changed": true,
        "description": "This is my new VLAN 1.",
        "failed": false,
        "id": "6fbb33c1-bc30-45da-a04e-06f64c1ee388",
        "metro": {
            "href": "/metal/v1/locations/metros/108b2cfb-246b-45e3-885a-bf3e82fce1a0",
            "id": "108b2cfb-246b-45e3-885a-bf3e82fce1a0"
        },
        "vxlan": 1234
    }
}

TASK [metal_virtual_circuit : create first virtual circuit for test] ***********
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Invalid UUID for connection_id: "}
```

2024-03-06 20:02 UTC, displague commented
Needs a rebase @antoninrykalsky

2024-03-07 20:36 UTC, ctreatma commented on tests/integration/targets/metal_virtual_circuit/tasks/main.yml
> +        name: "{{ test_virtual_circuit_name }}"
Looks like CI is failing here; should `test_virtual_circuit_name` be defined by the time this line is reached, or should this be a reference to something like `first_virtual_circuit.name`?

2024-03-07 20:38 UTC, ctreatma commented on tests/integration/targets/metal_virtual_circuit/tasks/main.yml
> +        name: "{{ test_virtual_circuit_name }}"
Or maybe this is meant to be `test_circuit_name`? https://github.com/equinix-labs/ansible-collection-equinix/pull/141/files#diff-f66d1a8381458f8e62c2cb40b979f693ae7697846f1b6cbe0edd4fcbc33c3421R24

2024-03-07 20:39 UTC, ctreatma commented on tests/integration/targets/metal_virtual_circuit/tasks/main.yml
> +      equinix.cloud.metal_virtual_circuit:
This task is failing with `Error in metal_virtual_circuit: No mapper for resource type metal_virtual_circuit`.

2024-03-11 13:43 UTC, displague commented
```
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Error in metal_virtual_circuit: (422)\nReason: Unprocessable Entity\nHTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Cache-Control': 'no-cache', 'X-Request-Id': '9abf2fc49cfc86bab000d14dd78157e9', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'Content-Length': '73', 'Date': 'Fri, 08 Mar 2024 13:01:21 GMT', 'Connection': 'close'})\nHTTP response body: {\"errors\":[\"Metro VLAN 9b5fdbb3-f0a8-492e-b7b8-a4d27b3a7087 not found.\"]}\n"}
```

Is this a flake or was the wrong VLAN ID referenced (or perhaps the wrong VLAN/VXLAN format?)

2024-03-11 14:52 UTC, ctreatma commented on tests/integration/targets/metal_virtual_circuit/tasks/main.yml
> +        test_metro: 'am'
For dedicated connection tests, we need to read the metro from the connection details rather than setting it as a fact so that we create all temporary test infrastructure in the same metro as the connection.

2024-03-14 15:24 UTC, ctreatma commented
@antoninrykalsky the metal-python SDK was recently upgraded and this will need a rebase to pull in those changes.  The upgraded SDK is able to differentiate between VLAN and VRF virtual circuits.

2024-03-18 13:27 UTC, t0mk requested changes

2024-03-19 11:26 UTC, antoninrykalsky commented on plugins/modules/metal_virtual_circuit_info.py
> +result_sample = ['''
Thanks, I changed it in the non-info module and forgot it here. I'll not use suggested change, there are missing second part of '''.

2024-03-19 11:29 UTC, antoninrykalsky commented on plugins/modules/metal_virtual_circuit_info.py
> +specdoc_examples = ['''
done

2024-03-19 11:33 UTC, antoninrykalsky commented on plugins/modules/metal_virtual_circuit.py
> +           'VNID VLAN parameter, see the <a href="https://metal.equinix.com/developers/docs/networking/fabric/" target="blank">documentation for Equinix Fabric.</a>'
Done. But.. my markdown for console `glow` is able to display it right. Just without hyperlink
![image](https://github.com/equinix-labs/ansible-collection-equinix/assets/1780994/44f76544-114e-4b43-8b06-5090d1969c54)

2024-03-19 11:39 UTC, antoninrykalsky commented on tests/integration/targets/metal_virtual_circuit/tasks/main.yml
> +        organization_id: "{{ orgs.resources[0].id }}"
yes sure

2024-03-19 17:37 UTC, ctreatma reviewed
@antoninrykalsky lgtm but needs a rebase.

2024-03-20 13:56 UTC, t0mk approved these changes

2024-03-20 13:57 UTC, merged