feat: metal vrf
equinix-labs/ansible-collection-equinix pull request #143
Opened 2023-11-27 14:22 UTC by antoninrykalsky

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf_info.py
> +    name=SpecField(
Right, name filter does not work well. On the negative side, if a non-existent name is passed, all vrfs are returned. 

```

    - name: filter by name / get VRF info
      equinix.cloud.metal_vrf_info:
        name: "{{ test_prefix }}"
        project_id: "{{ test_project.id }}"
      register: vrf_list

    - name: filter by name / assert
      assert:
        that:
        - "vrf_list.resources|length == 1"

    - name: filter by name / get non existing VRF info
      equinix.cloud.metal_vrf_info:
        name: "nonexisting"
        project_id: "{{ test_project.id }}"
      register: vrf_list1

    - name: filter by name / debug
      debug:
        var: vrf_list1

    - name: filter by name / assert nonexiting
      assert:
        that:
        - "vrf_list1.resources|length == 0"
```

I have removed that block from `module_spec` 
```
    name=SpecField(
        type=FieldType.string,
        description=['Filter VRF on substring in name attribute.'],
    ),
```

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf_info.py
> +- name: Gather information about all resources in parent resource
replaced

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf_info.py
> +        description=['Project ID where the VRF will be deployed.'],
replaced

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +# module, for example "metal_vlan".
removed

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +# Replace all occurrences of "metal_resource" with the name of the new
removed

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +# It is meant to be copied and modified to create a new module.
removed

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +# This is a template for a new module. It is not meant to be used as is.
removed, thx

2023-12-11 09:14 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +        'Create a VRF in your desired metro and project with any IP ranges that you want the VRF to route and forward.'
replaced, thx

2023-12-11 09:14 UTC, antoninrykalsky commented on tests/integration/targets/metal_vrf/tasks/main.yml
> +    - name: get VRF info
Fixed. I've copied it from metal_vlan, but it contains that check.

2023-12-12 16:10 UTC, t0mk requested changes

2023-12-12 16:10 UTC, t0mk commented on plugins/modules/metal_vrf.py
> +    type: str
There's more parameters to VRF:

https://github.com/equinix-labs/metal-python/blob/v0.3.0/equinix_metal/equinix_metal/models/vrf_create_input.py#L25
-   bgp_dynamic_neighbors_bfd_enabled
-   bgp_dynamic_neighbors_enabled
-   bgp_dynamic_neighbors_export_route_map

Some of the arguments of VRF are editable:
https://github.com/equinix-labs/metal-python/blob/v0.3.0/equinix_metal/equinix_metal/models/vrf_update_input.py#L28

They should be marked ` editable=True`

2023-12-12 19:10 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +    type: str
Well, yeah, I was basing it on Terraform, on this 

https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_vrf

there's nothing in there about those features. I'm going to have to look into this more in depth, it falls to me

```
pydantic.error_wrappers.ValidationError: 1 validation error for FindVrfs
id       
  field required (type=value_error.missing)
fatal: [testhost]: FAILED! => {
    "changed": false,                  
    "invocation": {
        "module_args": {                                                        
            "bgp_dynamic_neighbors_bfd_enabled": true,                                                                                                                            
            "bgp_dynamic_neighbors_enabled": true,                                                         
            "bgp_dynamic_neighbors_export_route_map": true,
            "description": "Test VRF with ASN 65000",
            "id": null,                                 
            "ip_ranges": [                                                                                                                                                                                                                                                   
                "192.168.100.0/25",
                "192.168.200.0/25"
            ],                        
            "local_asn": 65000,
            "metal_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "metal_api_url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "metal_ua_prefix": "",               
            "metro": "am",
            "name": "ansible-integration-test-vrf-2r8qp35j",
            "project_id": null,              
            "state": "present" 
        }                                                
    },                                                               
    "msg": "Error in metal_vrf: 1 validation error for FindVrfs\nid\n  field required (type=value_error.missing)"
}                                 

```

2023-12-13 08:46 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +    type: str
```
fatal: [testhost]: FAILED! => {                                                                                                                                                   
    "changed": false,
    "invocation": {   
        "module_args": {                                      
            "bgp_dynamic_neighbors_bfd_enabled": false,
            "bgp_dynamic_neighbors_enabled": false,
            "bgp_dynamic_neighbors_export_route_map": false,                    
            "description": "Test VRF with ASN 65000",                                                                                                                             
            "id": null,                                                                                    
            "ip_ranges": [                                                      
                "192.168.100.0/25",                                                                                                                                               
                "192.168.200.0/25"                                                                         
            ],                                                                                                                                                                                                                                                               
            "local_asn": 65000,                     
            "metal_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "metal_api_url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "metal_ua_prefix": "",    
            "metro": "am",
            "name": "ansible-integration-test-vrf-dsyhw88h",
            "project_id": "406e3b46-608a-4d4c-b2eb-a6dc30a9c668",
            "state": "present"                   
        }               
    },                                       
    "msg": "Error in metal_vrf: attribute 'bgp_dynamic_neighbors_bfd_enabled' (to map to 'bgp_dynamic_neighbors_bfd_enabled') not found in response_dict: {'bill': False, 'created_at': datetime.datetime(2023, 12, 13, 8, 37, 58, tzinfo=datetime.timezone.utc), 'created_b$
': {'href': '/metal/v1/users/ae8b343c-8800-44ff-a31f-edd1a2cbf86d', 'id': 'ae8b343c-8800-44ff-a31f-edd1a2cbf86d'}, 'description': 'Test VRF with ASN 65000', 'href': '/metal/v1/vrfs/b3a19195-aede-4f9e-bf21-3bd24d91f75a', 'id': 'b3a19195-aede-4f9e-bf21-3bd24d91f75a', 'i$
_ranges': ['192.168.100.0/25', '192.168.200.0/25'], 'local_asn': 65000, 'metro': {'href': '/metal/v1/locations/metros/108b2cfb-246b-45e3-885a-bf3e82fce1a0', 'id': '108b2cfb-246b-45e3-885a-bf3e82fce1a0'}, 'name': 'ansible-integration-test-vrf-dsyhw88h', 'project': {'hr$
f': '/metal/v1/projects/406e3b46-608a-4d4c-b2eb-a6dc30a9c668', 'id': '406e3b46-608a-4d4c-b2eb-a6dc30a9c668'}, 'tags': [], 'updated_at': datetime.datetime(2023, 12, 13, 8, 37, 58, tzinfo=datetime.timezone.utc), 'virtual_circuits': []}"
}

2023-12-13 15:47 UTC, t0mk commented on plugins/modules/metal_vrf.py
> +    type: str
Yes, the bgp flags are not present in response, let's skip.

2023-12-13 15:48 UTC, t0mk approved these changes

2023-12-13 16:06 UTC, t0mk requested changes

2023-12-13 16:06 UTC, t0mk commented on plugins/modules/metal_vrf.py
> +            "metal_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
We tend to keep the result sample simple - we only put here the dict from the `module_args`, without the `metal_*` keys. Please make the item in the result_sample list look just like that. Example in metal_project:

https://github.com/equinix-labs/ansible-collection-equinix/blob/main/plugins/modules/metal_project.py#L175

2023-12-13 17:33 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +            "metal_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
got it

2023-12-13 17:37 UTC, antoninrykalsky commented on plugins/modules/metal_vrf.py
> +    type: str
I have removed it

2023-12-14 09:43 UTC, t0mk approved these changes

2023-12-14 09:45 UTC, merged